[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  Access-Control-Allow-Origin = "https://task-tracker-plus-web.netlify.app"
  Access-Control-Allow-Credentials = "true"