[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
